### ISSUE TITLE
Receive FS Error

### ISSUE THREAD

**Issue by Squirrelcoding** [Squirrelcoding/Wordsearch#1]
lol I already found a bug on my own project

Whenever running the project, you receive an error similar to this:
```
fs.js:153
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:153:11)
    at Object.mkdir (fs.js:892:14)
    at Object.<anonymous> (/home/runner/Wordsearch/index.js:13:6)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_CALLBACK'
}
```

This is due to a type error (like the error suggests). I will fix this later and for now, just change `fs.mkdir('hi')` on line 13 to `fs.mkdirSync('hi')`

**Comment by Squirrelcoding** [comment]
resolved
